version: '3.7'
services:
  webapp:
    build:
      context: simple-object-storage
    ports:
    - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://object-storage-mongo:27017/sos
    depends_on:
    - db
    volumes:
    - ./storage:/app/storage
    container_name: object-storage-webapp
    restart: on-failure

  db:
    image: mongo
    container_name: object-storage-mongo
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_DATABASE=sos
    volumes:
    - ./mongodb:/data/db
    - ./mongoconfig:/data/configdb
    restart: on-failure

  redis:
    image: redis:4-alpine
    ports:
      - '6379:6379'
  worker:
    build:
      context: m1
    depends_on:
      - "redis"
    environment:
      - REDIS_QUEUE=redis

  queue-wrapper:
    build:
      context: m2
    depends_on:
      - "redis"
    environment:
      - REDIS_QUEUE=redis
    ports:
      - '5000:5000'
